# Setup
title:        Jaeger
tagline:      Uber's Distributed Tracing System
baseurl:      "/jaeger"
paginate:     1

# About/contact
author:
  name:       Uber Technologies, Inc
  url:        http://eng.uber.com

# Gems
gems:
  - jekyll-paginate

# Others
markdown: kramdown
